### ISSUE TITLE
error  'wx' is not defined  no-undef

### ISSUE THREAD

**Issue by shangdev** [zlm919/echarts-for-wechat-wepy#2]
引用后，提示wx is not defined，，在组件echarts.wpy中。

**Comment by zlm919** [comment]
@shangdev 
[改了一下](https://github.com/zlm919/echarts-for-wechat-wepy/commit/7600cc4aa70faface7658e10e809c7a5db8190d0)

**Comment by shangdev** [comment]
非常感谢
